[library.fusesoc-cores]
location = fusesoc_libraries/fusesoc-cores
sync-uri = https://github.com/fusesoc/fusesoc-cores
sync-type = git
auto-sync = true

[library.intgen]
location = fusesoc_libraries/intgen
sync-uri = https://github.com/stffrdhrn/intgen.git
sync-type = git
auto-sync = true

[library.elf-loader]
location = fusesoc_libraries/elf-loader
sync-uri = https://github.com/fusesoc/elf-loader.git
sync-type = git
auto-sync = true

[library.mor1kx-generic]
location = fusesoc_libraries/mor1kx-generic
sync-uri = https://github.com/stffrdhrn/mor1kx-generic.git
sync-type = git
auto-sync = true

[library.or1k_marocchino]
location = fusesoc_libraries/or1k_marocchino
sync-uri = https://github.com/openrisc/or1k_marocchino.git
sync-type = git
auto-sync = true

[library.mor1kx]
location = fusesoc_libraries/mor1kx
sync-uri = https://github.com/openrisc/mor1kx.git
sync-type = git
auto-sync = true

