# Copyright (C) 2014 Embecosm Limited.

# Contributor Pierre Langlois <pierre.langlois@embecosm.com>

# This file is part of Embench and was formerly part of the Bristol/Embecosm
# Embedded Benchmark Suite.

# SPDX-License-Identifier: GPL-3.0-or-later

# Set timeout based on optional environment variable.

if { [llength [array names env BEEBS_TIMEOUT]] > 0 } {
    set timeout $env(BEEBS_TIMEOUT)
    verbose "BEEBS_TIMEOUT set to $timeout"
}

foreach target $target_list {
    beebs_run_all_benchmarks $target ${objdir}/../src
}
